version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: "/sdk"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/wallet"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
